name: first workflow
on:
  push:
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "event context" - ${{ toJSON(github.event) }}
  hello-world2:
    runs-on: ubuntu-latest
    needs: [hello-world]
    if: success()
    steps:
      - name: First step
        run: echo "Hello, world2!"
  hello-world3:
    runs-on: ubuntu-latest
    needs: [hello-world]
    steps:
      - name: First step
        run: echo "Hello, world3!"
      - name: Fail job
        run: exit 1
  hello-world4:
    runs-on: ubuntu-latest
    needs: [hello-world2, hello-world3]
    if: success()
    steps:
      - name: First step
        run: echo "Hello, world4!"
    
